/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#e7e5f1",
        "tertiary-fixed": "#e3e1ed",
        "secondary": "#006e2f",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#4ae176",
        "inverse-primary": "#d2bbff",
        "on-surface-variant": "#4a4455",
        "on-surface": "#1d1a24",
        "background": "#fef7ff",
        "on-primary-fixed-variant": "#5a00c6",
        "error": "#ba1a1a",
        "on-primary-fixed": "#25005a",
        "inverse-surface": "#332f39",
        "outline": "#7b7487",
        "on-secondary-fixed": "#002109",
        "on-tertiary-fixed": "#1a1b23",
        "tertiary-fixed-dim": "#c7c5d1",
        "tertiary-container": "#666670",
        "surface-container-high": "#ede5f4",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#005321",
        "surface-container-low": "#f9f1ff",
        "surface-bright": "#fef7ff",
        "on-secondary-container": "#007432",
        "surface-container": "#f3ebfa",
        "tertiary": "#4e4e58",
        "surface-variant": "#e8dfee",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#d2bbff",
        "primary-container": "#7c3aed",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f6eefc",
        "on-tertiary": "#ffffff",
        "primary": "#630ed4",
        "surface": "#fef7ff",
        "on-primary-container": "#ede0ff",
        "secondary-fixed": "#6bff8f",
        "surface-container-highest": "#e8dfee",
        "surface-tint": "#732ee4",
        "primary-fixed": "#eaddff",
        "outline-variant": "#ccc3d8",
        "surface-dim": "#dfd7e6",
        "on-error-container": "#93000a",
        "on-background": "#1d1a24",
        "on-tertiary-fixed-variant": "#46464f",
        "secondary-container": "#6bff8f",
        "surface-container-lowest": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "card": "24px",
        "button": "16px"
      },
      spacing: {
        "container-max": "1280px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "margin-mobile": "16px",
        "gutter": "24px",
        "stack-md": "16px",
        "section-gap-desktop": "140px",
        "section-gap-mobile": "80px"
      },
      fontFamily: {
        "sans": ['Inter', 'sans-serif'],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Plus Jakarta Sans"],
        "display-xl": ["Plus Jakarta Sans"],
        "label-bold": ["Inter"],
        "headline-md": ["Plus Jakarta Sans"],
        "display-xl-mobile": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "display-xl": ["60px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "label-bold": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["36px", {"lineHeight": "44px", "fontWeight": "700"}],
        "display-xl-mobile": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "800"}]
      }
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
